DROP DATABASE IF EXISTS CELLS_IO;
CREATE DATABASE CELLS_IO;
USE CELLS_IO;


CREATE TABLE PLAYER
(
PLAYER_ID INT(3) NOT NULL PRIMARY KEY,
NOM CHAR(16) NOT NULL,
RADIUS INT (3) NOT NULL,
X INT (4) NOT NULL,
Y INT (4) NOT NULL
);
