CREATE DATABASE CELLS_IO;
USE CELLS_IO;

CREATE TABLE PLAYER
(
PLAYER_ID INT(3) NOT NULL PRIMARY KEY,
NOM CHAR(16) NOT NULL,
RADIUS INT (3) NOT NULL,
X INT (4) NOT NULL,
Y INT (4) NOT NULL
);

CREATE TABLE CONNECTION_INFO
(
ADRESSE_IP NVARCHAR(13) NOT NULL PRIMARY KEY,
PLAYER_ID INT(3) NOT NULL,
FOREIGN KEY PLAYER_ID (PLAYER_ID)
REFERENCES PLAYER(PLAYER_ID)
);

INSERT INTO PLAYER (PLAYER_ID, NOM, RADIUS, X, Y)
VALUES (0, 'MATHIEU', 8, 250, 250);

INSERT INTO CONNECTION_INFO (ADRESSE_IP, PLAYER_ID)
VALUES ('192.168.1.2',0);